version: '3.4'

services:
  moviestore.api:
    image: ${DOCKER_REGISTRY-}moviestoreapi
    build:
      context: .
      dockerfile: src/MovieStore.Api/Dockerfile
    ports: 
      - 5400:8080
      - 5401:8081
    depends_on: 
      - sqlserver
  sqlserver:
    restart: unless-stopped
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      MSSQL_SA_PASSWORD: "P@ssword123"
      ACCEPT_EULA: "Y"
    ports:
      - 5050:1433
