version: '3.4'

services:
  moviestore.api:
    image: ${DOCKER_REGISTRY-}moviestoreapi
    build:
      context: .
      dockerfile: src/MovieStore.Api/Dockerfile
    ports: 
      - 5400:8080
      - 5401:8081
